##############################################################################
# Module manifest for module 'ircMessenger'
# Generated by: Chuck Spencer Jr.
# Generated on: 11/12/17
# Updated on: 03/03/18
##############################################################################

@{

    # Script module or binary module file associated with this manifest.
    RootModule        = 'IrcMsg.psm1'

    # Version number of this module.
    ModuleVersion     = '0.0.2'

    # ID used to uniquely identify this module
    GUID              = '09baf2b1-add2-4eee-8ee9-35b1774344df'

    # Author of this module
    Author            = 'Chuck Spencer Jr.'

    # Company or vendor of this module
    CompanyName       = 'Spencer Jr.'

    # Copyright statement for this module
    Copyright         = '(c) Chuck Spencer. All rights reserved.'

    # Description of the functionality provided by this module
    # Description = ''

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @(
        "Connect-IrcServer",
        "Disconnect-IrcServer",
        "Send-IrcMessage",
        "Read-IrcMessage", 
        "Connect-IrcChannel",
        "Disconnect-IrcChannel",
        "Send-IrcPrivMsg",
        "Send-IrcNotice"
    )

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    CmdletsToExport   = @()

    # Variables to export from this module
    VariablesToExport = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    AliasesToExport   = @()

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}

